apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sharan-naidu/inventory-management-system-devops.git
    targetRevision: main
    path: helm/inventory

  destination:
    server: https://kubernetes.default.svc
    namespace: inventory

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
